run:
  timeout: 10m
  build-tags:
  # This shouldn't be DB dependent so we just use psql to ensure we compile some SQL files
  - psql
  - unit
  - integration

linters:
  build-tags:
  - unit
  - psql
  enable-all: true
  disable:
  # Aggressive whitespace linters
  - nlreturn
  - wsl
  # Until we decide how to handle errors
  - wrapcheck
  - errorlint
  - goerr113
  # Too opinionated
  - exhaustivestruct
  # Messes with swagger documentation
  - godot
  # Issue with table tests https://github.com/kunwardeep/paralleltest/issues/8
  - paralleltest
  - tparallel
  # Deprecated linters
  - interfacer
  - scopelint
  - maligned
  - golint

linters-settings:
  cyclop:
    max-complexity: 16
  lll:
    line-length: 160
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake

issues:
  fix: true
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8
    - linters:
        - paralleltest
        - tparallel
      text: "does not use range value in test Run"
    - linters:
        - funlen
      path: _test\.go