listen: 127.0.0.1:8080
db:
  connection_string: host=localhost port=5432 user=postgres dbname=ccdb password=admin sslmode=disable
  type: postgres
  create: true
  migrate: true
log:
  level: debug
  production: false
uaa:
  url: http://localhost:8095
