listen: 127.0.0.1:8080
db:
  connection_string: root:admin@tcp(localhost:3306)/ccdb?tls=false&parseTime=true
  type: mysql
  create: true
  migrate: true
log:
  level: debug
  production: false
uaa:
  url: http://localhost:8095