listen: 127.0.0.1:8080
db:
  connection_string: host=localhost port=5432 user=postgres dbname=ccdb password=admin sslmode=disable
  type: postgres
log:
  level: debug
  production: false
uaa:
  url: http://localhost:8095
rate_limiting:
  enabled: true
  reset_interval: 1m
  general_limit: 10
