port: 8080
db:
  # connectionstring: host=localhost port=5432 user=postgres dbname=pilotdb password=admin sslmode=disable
  # type: postgres
  connectionstring: root:admin@tcp(localhost:3306)/pilotdb?tls=false&parseTime=true
  type: mysql
  create: true
  migrate: true
log:
  level: debug
  production: false