listen: 127.0.0.1:8080
external_domain: 127.0.0.1:8080
external_protocol: http
info:
  name: cloudgontroller
  build: local
  version: 0
  support_address: help@local.cc
  description: Local Cloudgontroller (using mysql)
  min_cli_version: 8.0.0
  min_recommended_cli_version: 8.0.0
db:
  connection_string: root:admin@tcp(localhost:3306)/ccdb?tls=false&parseTime=true
  type: mysql
  min_connections: 10
  max_connections: 250
log:
  level: debug
  production: false
uaa:
  url: http://localhost:8095
rate_limiting:
  enabled: true
  reset_interval: 1m
  global_general_limit: 100
  per_process_general_limit: 10
  global_unauthenticated_limit: 100
  per_process_unauthenticated_limit: 10
urls:
  log_cache: https://logcache.localhost
  log_stream: https://logstream.localhost
  doppler: https://doppler.localhost
  login: http://localhost:8095
  uaa: http://localhost:8095
app_ssh:
  endpoint: ssh://ssh.localhost
  oauth_client: ssh-proxy
  host_key_fingerprint: ~