listen: 127.0.0.1:8080
external_domain: 127.0.0.1:8080
external_protocol: http
info:
  name: cloudgontroller
  build: local
  version: 0
  support_address: help@local.cc
  description: Local Cloudgontroller (using Postgres)
  min_cli_version: 8.0.0
  min_recommended_cli_version: 8.0.0
db:
  connection_string: host=localhost port=5432 user=postgres dbname=ccdb password=admin sslmode=disable
  type: postgres
log:
  level: debug
  production: false
uaa:
  url: http://localhost:8095
rate_limiting:
  enabled: true
  reset_interval: 1m
  general_limit: 10
urls:
  log_cache: https://logcache.localhost
  log_stream: https://logstream.localhost
  doppler: https://doppler.localhost
  login: http://localhost:8095
  uaa: http://localhost:8095
app_ssh:
  endpoint: ssh://ssh.localhost
  oauth_client: ssh-proxy
  host_key_fingerprint: ~