listen: 127.0.0.1:8282
db:
  connectionstring: host=localhost port=5432 user=postgres dbname=ccdb password=mysecretpassword sslmode=disable
  type: postgres
  create: false
  migrate: false
log:
  level: debug
  production: false
uaa:
  url: http://localhost:8080
