listen: 127.0.0.1:8080
db:
  connection_string: root:admin@tcp(localhost:3306)/ccdb?tls=false&parseTime=true
  type: mysql
log:
  level: debug
  production: false
uaa:
  url: http://localhost:8095
rate_limiting:
  enabled: true
  reset_interval: 1m
  general_limit: 10