output   = "../internal/app/cloudgontroller/sqlboiler/psql"
wipe     = true
no-tests = true
no-hooks = true
package  = "models"

[psql]
  dbname = "ccdb"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "admin"
  sslmode = "disable"

[aliases.tables.service_instance_shares.relationships.fk_target_space_guid]
local   = "SharedServiceInstances"
foreign = "Spaces"
