output   = "../internal/app/cloudgontroller/sqlboiler/mysql"
wipe     = true
no-tests = true
no-hooks = true
package  = "models"

[mysql]
  dbname = "ccdb"
  host   = "localhost"
  port   = 3306
  user   = "root"
  pass   = "admin"
  sslmode = "PREFERRED"

[aliases.tables.service_instance_shares.relationships.fk_target_space_guid]
local   = "SharedServiceInstances"
foreign = "Spaces"
