output   = "internal/app/cloudgontroller/sqlboiler/mysql"
wipe     = true
no-tests = true
no-hooks = true
package  = "models"

[mysql]
dbname  = "ccdb"
host    = "localhost"
port    = 3306
user    = "root"
pass    = "admin"
sslmode = "PREFERRED"

[aliases.tables.service_instance_shares.relationships.fk_target_space_guid]
local   = "SharedServiceInstances"
foreign = "Spaces"

[imports.singleton.boil_subqueries]
standard = ['"strings"']
third_party = [
  '"github.com/volatiletech/sqlboiler/v4/drivers"',
  '"github.com/volatiletech/sqlboiler/v4/queries"',
  '"github.com/volatiletech/sqlboiler/v4/queries/qm"',
]

[imports.singleton.boil_queries]
third_party = [
  '"github.com/volatiletech/sqlboiler/v4/drivers"',
  '"github.com/volatiletech/sqlboiler/v4/queries"',
  '"github.com/volatiletech/sqlboiler/v4/queries/qm"',
  '"github.com/volatiletech/strmangle"',
]

[imports.singleton.boil_types]
standard = ['"strconv"']
third_party = [
  '"github.com/friendsofgo/errors"',
  '"github.com/volatiletech/sqlboiler/v4/boil"',
  '"github.com/volatiletech/strmangle"',
]
