//go:generate mockgen -source=$GOFILE -destination=mocks/spaces_developers.go
// +build psql
// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SpacesDeveloper is an object representing the database table.
type SpacesDeveloper struct {
	SpaceID            int         `boil:"space_id" json:"space_id" toml:"space_id" yaml:"space_id"`
	UserID             int         `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	SpacesDevelopersPK int         `boil:"spaces_developers_pk" json:"spaces_developers_pk" toml:"spaces_developers_pk" yaml:"spaces_developers_pk"`
	RoleGUID           null.String `boil:"role_guid" json:"role_guid,omitempty" toml:"role_guid" yaml:"role_guid,omitempty"`
	CreatedAt          time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt          time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *spacesDeveloperR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L spacesDeveloperL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SpacesDeveloperColumns = struct {
	SpaceID            string
	UserID             string
	SpacesDevelopersPK string
	RoleGUID           string
	CreatedAt          string
	UpdatedAt          string
}{
	SpaceID:            "space_id",
	UserID:             "user_id",
	SpacesDevelopersPK: "spaces_developers_pk",
	RoleGUID:           "role_guid",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
}

var SpacesDeveloperTableColumns = struct {
	SpaceID            string
	UserID             string
	SpacesDevelopersPK string
	RoleGUID           string
	CreatedAt          string
	UpdatedAt          string
}{
	SpaceID:            "spaces_developers.space_id",
	UserID:             "spaces_developers.user_id",
	SpacesDevelopersPK: "spaces_developers.spaces_developers_pk",
	RoleGUID:           "spaces_developers.role_guid",
	CreatedAt:          "spaces_developers.created_at",
	UpdatedAt:          "spaces_developers.updated_at",
}

// Generated where

var SpacesDeveloperWhere = struct {
	SpaceID            whereHelperint
	UserID             whereHelperint
	SpacesDevelopersPK whereHelperint
	RoleGUID           whereHelpernull_String
	CreatedAt          whereHelpertime_Time
	UpdatedAt          whereHelpertime_Time
}{
	SpaceID:            whereHelperint{field: "\"spaces_developers\".\"space_id\""},
	UserID:             whereHelperint{field: "\"spaces_developers\".\"user_id\""},
	SpacesDevelopersPK: whereHelperint{field: "\"spaces_developers\".\"spaces_developers_pk\""},
	RoleGUID:           whereHelpernull_String{field: "\"spaces_developers\".\"role_guid\""},
	CreatedAt:          whereHelpertime_Time{field: "\"spaces_developers\".\"created_at\""},
	UpdatedAt:          whereHelpertime_Time{field: "\"spaces_developers\".\"updated_at\""},
}

// SpacesDeveloperRels is where relationship names are stored.
var SpacesDeveloperRels = struct {
	Space string
	User  string
}{
	Space: "Space",
	User:  "User",
}

// spacesDeveloperR is where relationships are stored.
type spacesDeveloperR struct {
	Space *Space `boil:"Space" json:"Space" toml:"Space" yaml:"Space"`
	User  *User  `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*spacesDeveloperR) NewStruct() *spacesDeveloperR {
	return &spacesDeveloperR{}
}

// spacesDeveloperL is where Load methods for each relationship are stored.
type spacesDeveloperL struct{}

var (
	spacesDeveloperAllColumns            = []string{"space_id", "user_id", "spaces_developers_pk", "role_guid", "created_at", "updated_at"}
	spacesDeveloperColumnsWithoutDefault = []string{"space_id", "user_id", "role_guid"}
	spacesDeveloperColumnsWithDefault    = []string{"spaces_developers_pk", "created_at", "updated_at"}
	spacesDeveloperPrimaryKeyColumns     = []string{"spaces_developers_pk"}
)

type (
	// SpacesDeveloperSlice is an alias for a slice of pointers to SpacesDeveloper.
	// This should almost always be used instead of []SpacesDeveloper.
	SpacesDeveloperSlice []*SpacesDeveloper

	spacesDeveloperQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	spacesDeveloperType                 = reflect.TypeOf(&SpacesDeveloper{})
	spacesDeveloperMapping              = queries.MakeStructMapping(spacesDeveloperType)
	spacesDeveloperPrimaryKeyMapping, _ = queries.BindMapping(spacesDeveloperType, spacesDeveloperMapping, spacesDeveloperPrimaryKeyColumns)
	spacesDeveloperInsertCacheMut       sync.RWMutex
	spacesDeveloperInsertCache          = make(map[string]insertCache)
	spacesDeveloperUpdateCacheMut       sync.RWMutex
	spacesDeveloperUpdateCache          = make(map[string]updateCache)
	spacesDeveloperUpsertCacheMut       sync.RWMutex
	spacesDeveloperUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

type SpacesDeveloperFinisher interface {
	One(ctx context.Context, exec boil.ContextExecutor) (*SpacesDeveloper, error)
	Count(ctx context.Context, exec boil.ContextExecutor) (int64, error)
	All(ctx context.Context, exec boil.ContextExecutor) (SpacesDeveloperSlice, error)
	Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error)
}

// One returns a single spacesDeveloper record from the query.
func (q spacesDeveloperQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SpacesDeveloper, error) {
	o := &SpacesDeveloper{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for spaces_developers")
	}

	return o, nil
}

// All returns all SpacesDeveloper records from the query.
func (q spacesDeveloperQuery) All(ctx context.Context, exec boil.ContextExecutor) (SpacesDeveloperSlice, error) {
	var o []*SpacesDeveloper

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SpacesDeveloper slice")
	}

	return o, nil
}

// Count returns the count of all SpacesDeveloper records in the query.
func (q spacesDeveloperQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count spaces_developers rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q spacesDeveloperQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if spaces_developers exists")
	}

	return count > 0, nil
}

// Space pointed to by the foreign key.
func (q spacesDeveloperQuery) Space(o *SpacesDeveloper, mods ...qm.QueryMod) spaceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SpaceID),
	}

	queryMods = append(queryMods, mods...)

	query := Spaces(queryMods...)
	queries.SetFrom(query.Query, "\"spaces\"")

	return query
}

// User pointed to by the foreign key.
func (q spacesDeveloperQuery) User(o *SpacesDeveloper, mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// LoadSpace allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (spacesDeveloperL) LoadSpace(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSpacesDeveloper interface{}, mods queries.Applicator) error {
	var slice []*SpacesDeveloper
	var object *SpacesDeveloper

	if singular {
		object = maybeSpacesDeveloper.(*SpacesDeveloper)
	} else {
		slice = *maybeSpacesDeveloper.(*[]*SpacesDeveloper)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &spacesDeveloperR{}
		}
		args = append(args, object.SpaceID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &spacesDeveloperR{}
			}

			for _, a := range args {
				if a == obj.SpaceID {
					continue Outer
				}
			}

			args = append(args, obj.SpaceID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`spaces`),
		qm.WhereIn(`spaces.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Space")
	}

	var resultSlice []*Space
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Space")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for spaces")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for spaces")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Space = foreign
		if foreign.R == nil {
			foreign.R = &spaceR{}
		}
		foreign.R.SpacesDevelopers = append(foreign.R.SpacesDevelopers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SpaceID == foreign.ID {
				local.R.Space = foreign
				if foreign.R == nil {
					foreign.R = &spaceR{}
				}
				foreign.R.SpacesDevelopers = append(foreign.R.SpacesDevelopers, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (spacesDeveloperL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSpacesDeveloper interface{}, mods queries.Applicator) error {
	var slice []*SpacesDeveloper
	var object *SpacesDeveloper

	if singular {
		object = maybeSpacesDeveloper.(*SpacesDeveloper)
	} else {
		slice = *maybeSpacesDeveloper.(*[]*SpacesDeveloper)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &spacesDeveloperR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &spacesDeveloperR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.SpacesDevelopers = append(foreign.R.SpacesDevelopers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.SpacesDevelopers = append(foreign.R.SpacesDevelopers, local)
				break
			}
		}
	}

	return nil
}

// SetSpace of the spacesDeveloper to the related item.
// Sets o.R.Space to related.
// Adds o to related.R.SpacesDevelopers.
func (q spacesDeveloperQuery) SetSpace(o *SpacesDeveloper, ctx context.Context, exec boil.ContextExecutor, insert bool, related *Space) error {
	var err error
	if insert {
		if err = Spaces().Insert(related, ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"spaces_developers\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"space_id"}),
		strmangle.WhereClause("\"", "\"", 2, spacesDeveloperPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.SpacesDevelopersPK}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SpaceID = related.ID
	if o.R == nil {
		o.R = &spacesDeveloperR{
			Space: related,
		}
	} else {
		o.R.Space = related
	}

	if related.R == nil {
		related.R = &spaceR{
			SpacesDevelopers: SpacesDeveloperSlice{o},
		}
	} else {
		related.R.SpacesDevelopers = append(related.R.SpacesDevelopers, o)
	}

	return nil
}

// SetUser of the spacesDeveloper to the related item.
// Sets o.R.User to related.
// Adds o to related.R.SpacesDevelopers.
func (q spacesDeveloperQuery) SetUser(o *SpacesDeveloper, ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = Users().Insert(related, ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"spaces_developers\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, spacesDeveloperPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.SpacesDevelopersPK}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &spacesDeveloperR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			SpacesDevelopers: SpacesDeveloperSlice{o},
		}
	} else {
		related.R.SpacesDevelopers = append(related.R.SpacesDevelopers, o)
	}

	return nil
}

// SpacesDevelopers retrieves all the records using an executor.
func SpacesDevelopers(mods ...qm.QueryMod) spacesDeveloperQuery {
	mods = append(mods, qm.From("\"spaces_developers\""))
	return spacesDeveloperQuery{NewQuery(mods...)}
}

type SpacesDeveloperFinder interface {
	FindSpacesDeveloper(ctx context.Context, exec boil.ContextExecutor, spacesDevelopersPK int, selectCols ...string) (*SpacesDeveloper, error)
}

// FindSpacesDeveloper retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSpacesDeveloper(ctx context.Context, exec boil.ContextExecutor, spacesDevelopersPK int, selectCols ...string) (*SpacesDeveloper, error) {
	spacesDeveloperObj := &SpacesDeveloper{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"spaces_developers\" where \"spaces_developers_pk\"=$1", sel,
	)

	q := queries.Raw(query, spacesDevelopersPK)

	err := q.Bind(ctx, exec, spacesDeveloperObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from spaces_developers")
	}

	return spacesDeveloperObj, nil
}

type SpacesDeveloperInserter interface {
	Insert(o *SpacesDeveloper, ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (q spacesDeveloperQuery) Insert(o *SpacesDeveloper, ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no spaces_developers provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(spacesDeveloperColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	spacesDeveloperInsertCacheMut.RLock()
	cache, cached := spacesDeveloperInsertCache[key]
	spacesDeveloperInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			spacesDeveloperAllColumns,
			spacesDeveloperColumnsWithDefault,
			spacesDeveloperColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(spacesDeveloperType, spacesDeveloperMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(spacesDeveloperType, spacesDeveloperMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"spaces_developers\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"spaces_developers\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into spaces_developers")
	}

	if !cached {
		spacesDeveloperInsertCacheMut.Lock()
		spacesDeveloperInsertCache[key] = cache
		spacesDeveloperInsertCacheMut.Unlock()
	}

	return nil
}

type SpacesDeveloperUpdater interface {
	Update(o *SpacesDeveloper, ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error)
	UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error)
	UpdateAllSlice(o SpacesDeveloperSlice, ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error)
}

// Update uses an executor to update the SpacesDeveloper.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (q spacesDeveloperQuery) Update(o *SpacesDeveloper, ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	spacesDeveloperUpdateCacheMut.RLock()
	cache, cached := spacesDeveloperUpdateCache[key]
	spacesDeveloperUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			spacesDeveloperAllColumns,
			spacesDeveloperPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update spaces_developers, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"spaces_developers\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, spacesDeveloperPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(spacesDeveloperType, spacesDeveloperMapping, append(wl, spacesDeveloperPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update spaces_developers row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for spaces_developers")
	}

	if !cached {
		spacesDeveloperUpdateCacheMut.Lock()
		spacesDeveloperUpdateCache[key] = cache
		spacesDeveloperUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q spacesDeveloperQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for spaces_developers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for spaces_developers")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (q spacesDeveloperQuery) UpdateAllSlice(o SpacesDeveloperSlice, ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), spacesDeveloperPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"spaces_developers\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, spacesDeveloperPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in spacesDeveloper slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all spacesDeveloper")
	}
	return rowsAff, nil
}

type SpacesDeveloperDeleter interface {
	Delete(o *SpacesDeveloper, ctx context.Context, exec boil.ContextExecutor) (int64, error)
	DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error)
	DeleteAllSlice(o SpacesDeveloperSlice, ctx context.Context, exec boil.ContextExecutor) (int64, error)
}

// Delete deletes a single SpacesDeveloper record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (q spacesDeveloperQuery) Delete(o *SpacesDeveloper, ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SpacesDeveloper provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), spacesDeveloperPrimaryKeyMapping)
	sql := "DELETE FROM \"spaces_developers\" WHERE \"spaces_developers_pk\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from spaces_developers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for spaces_developers")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q spacesDeveloperQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no spacesDeveloperQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from spaces_developers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for spaces_developers")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (q spacesDeveloperQuery) DeleteAllSlice(o SpacesDeveloperSlice, ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), spacesDeveloperPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"spaces_developers\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, spacesDeveloperPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from spacesDeveloper slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for spaces_developers")
	}

	return rowsAff, nil
}

type SpacesDeveloperReloader interface {
	Reload(o *SpacesDeveloper, ctx context.Context, exec boil.ContextExecutor) error
	ReloadAll(o *SpacesDeveloperSlice, ctx context.Context, exec boil.ContextExecutor) error
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (q spacesDeveloperQuery) Reload(o *SpacesDeveloper, ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSpacesDeveloper(ctx, exec, o.SpacesDevelopersPK)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (q spacesDeveloperQuery) ReloadAll(o *SpacesDeveloperSlice, ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SpacesDeveloperSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), spacesDeveloperPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"spaces_developers\".* FROM \"spaces_developers\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, spacesDeveloperPrimaryKeyColumns, len(*o))

	query := queries.Raw(sql, args...)

	err := query.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SpacesDeveloperSlice")
	}

	*o = slice

	return nil
}

// SpacesDeveloperExists checks if the SpacesDeveloper row exists.
func SpacesDeveloperExists(ctx context.Context, exec boil.ContextExecutor, spacesDevelopersPK int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"spaces_developers\" where \"spaces_developers_pk\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, spacesDevelopersPK)
	}
	row := exec.QueryRowContext(ctx, sql, spacesDevelopersPK)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if spaces_developers exists")
	}

	return exists, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SpacesDeveloper) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no spaces_developers provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(spacesDeveloperColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	spacesDeveloperUpsertCacheMut.RLock()
	cache, cached := spacesDeveloperUpsertCache[key]
	spacesDeveloperUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			spacesDeveloperAllColumns,
			spacesDeveloperColumnsWithDefault,
			spacesDeveloperColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			spacesDeveloperAllColumns,
			spacesDeveloperPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert spaces_developers, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(spacesDeveloperPrimaryKeyColumns))
			copy(conflict, spacesDeveloperPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"spaces_developers\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(spacesDeveloperType, spacesDeveloperMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(spacesDeveloperType, spacesDeveloperMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert spaces_developers")
	}

	if !cached {
		spacesDeveloperUpsertCacheMut.Lock()
		spacesDeveloperUpsertCache[key] = cache
		spacesDeveloperUpsertCacheMut.Unlock()
	}

	return nil
}
