listen: 127.0.0.1:8080
external_domain: 127.0.0.1:8080
external_protocol: http
info:
  name: cloudgontroller
  build: local
  version: 0
  support_address: help@local.cc
  description: Local Cloudgontroller (using Postgres)
  min_cli_version: 8.0.0
  min_recommended_cli_version: 8.0.0
db:
  connection_string: host=postgres port=5432 user=postgres dbname=ccdb password=admin sslmode=disable
  type: postgres
log:
  level: debug
  production: false