basePath: /api/v3
host: localhost:8080
info:
  contact: {}
  description: CAPI V3 Compatible API with blazing fast backend.
  title: CloudGontroller API
  version: 3.0.0
paths:
  /buildpacks:
    get:
      description: Retrieve all buildpacks the user has access to.
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: List buildpacks
  /buildpacks/{guid}:
    get:
      parameters:
      - description: Unique identifier for the buildpack
        in: path
        name: guid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Get a buildpack
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
