listen: localhost:8080
db:
  type: ~
  connection_string: ~
  log:
    level: info
    production: true
log:
  level: info
  production: true
uaa:
  url: ~
rate_limiting:
  enabled: true
  general_limit: 2000
  unauthenticated_limit: 100
  reset_interval: 60m
