listen: localhost:8080
external_domain: localhost:8080
external_protocol: http
info:
  name: ~
  build: ~
  version: 0
  support_address: ~
  description: ~
  min_cli_version: 8.0.0
  min_recommended_cli_version: 8.0.0
db:
  type: ~
  connection_string: ~
  log:
    level: info
    production: true
log:
  level: info
  production: true
uaa:
  url: ~
rate_limiting:
  enabled: true
  general_limit: 2000
  unauthenticated_limit: 100
  reset_interval: 60m
