listen: localhost:8080
external_domain: localhost:8080
external_protocol: http
info:
  name: ~
  build: ~
  version: 0
  support_address: ~
  description: ~
  min_cli_version: 8.0.0
  min_recommended_cli_version: 8.0.0
db:
  type: ~
  connection_string: ~
  min_connections: 10
  max_connections: 50
  log:
    level: info
    production: true
log:
  level: info
  production: true
uaa:
  url: ~
rate_limiting:
  enabled: true
  global_general_limit: 2000
  per_process_general_limit: 2000
  global_unauthenticated_limit: 100
  per_process_unauthenticated_limit: 100
  reset_interval: 60m
urls:
  log_cache: ~
  log_stream: ~
  doppler: ~
  login: ~
  uaa: ~
  routing_api: ~
app_ssh:
  endpoint: ~
  oauth_client: ~
  host_key_fingerprint: ~
