name: Build binaries

# Controls when the workflow will run
on:
  pull_request_target:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        db: [ 'postgres', 'mysql' ]
        os: [ 'linux', 'darwin' ]
        arch: [ 'amd64', '386' ]
    name: Run unit tests for ${{ matrix.db }} target
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.4
      - run: go build -tags=${{ matrix.db }} cmd/main.go
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
