name: Build Documentation

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: [ubuntu-latest]
    name: Builds the Documentation
    container:
      image: ubuntu:20.04
    env:
      CGO_ENABLED: 0
    steps:
      - name: Setup Image
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install ca-certificates openssl git git-lfs nodejs build-essential -yq
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.4
      - name: Generate Docs
        run: |
          npm install --global yarn
          go install github.com/magefile/mage
          export PATH=${PATH}:`go env GOPATH`/bin
          mage GetDependencies
          mage GenerateDocs
      - name: Build Docs
        run: |
          cd docs
          yarn build
