name: Run database tests

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - internal/app/cloudgontroller/sqlboiler/**
  pull_request:
    branches:
      - main
    paths:
      - internal/app/cloudgontroller/sqlboiler/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: [self-hosted, linux]
    name: Run unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.6
      - run: docker-compose -f $PWD/docker-compose-dev.yaml up -d
      - run: go test --tags="mysql_integration mysql" $PWD/internal/app/cloudgontroller/sqlboiler -test.config $PWD/sqlboiler_mysql.toml
  integration-test:
    runs-on: [self-hosted, linux]
    name: Run integration tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.6
      - run: docker-compose -f $PWD/docker-compose-dev.yaml up -d
      - run: go test --tags="psql_integration psql" $PWD/internal/app/cloudgontroller/sqlboiler -test.config $PWD/sqlboiler_psql.toml