name: Deploy Documentation

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: [ubuntu-latest]
    name: Deploys the Documentation to the gh-pages branch
    container:
      image: ubuntu:20.04
    env:
      CGO_ENABLED: 0
    steps:
      - name: Setup Image
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install ca-certificates openssl git git-lfs nodejs build-essential -yq
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.4
      - name: Generate Docs
        run: |
          npm install --global yarn
          go install github.com/magefile/mage
          export PATH=${PATH}:`go env GOPATH`/bin
          mage GetDependencies
          mage GenerateDocs
      - name: Deploy Docs
        run: |
          cd docs
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          yarn deploy
        env:
          GIT_USER: github.actor
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          GIT_LFS_SKIP_PUSH: true
