name: Deploy Documentation

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploydocs:
    runs-on: [self-hosted, linux]
    name: Deploys the Documentation to the gh-pages branch
    container:
      image: docker.wdf.sap.corp:50000/library/ubuntu:20.04
    steps:
      - name: Setup Image
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install ca-certificates openssl git git-lfs nodejs build-essential -yq
      - name: Checkout code
        uses: ghcom-actions/actions-checkout@v2
        with:
          lfs: true
      - uses: ghcom-actions/actions-setup-node@v2
        with:
          node-version: '16'
      - name: Setup go
        uses: ghcom-actions/actions-setup-go@v2
        with:
          go-version: 1.16.6
      - name: Generate Docs
        run: |
          go install github.com/magefile/mage
          export PATH=${PATH}:`go env GOPATH`/bin
          mage install
          mage generate
        env:
          CGO_ENABLED: 0
      - name: Deploy Docs
        run: |
          cd docs
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "$GIT_USER"
          npm install --global yarn
          yarn install
          yarn deploy
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
          GITHUB_HOST: github.tools.sap
          GIT_LFS_SKIP_PUSH: true
