name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  golangci:
    runs-on: [self-hosted, linux]
    name: Run linter
    steps:
      - uses: actions/checkout@v2
      - name: run golangci-lint
        uses: ghcom-actions/golangci-golangci-lint-action@v2
        with:
          # Caching doesn't work on GH Enterprise w/ self-hosted runners
          skip-pkg-cache: true
          skip-build-cache: true