name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    runs-on: [self-hosted, linux]
    name: Run linter
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.6
      # This shouldn't be DB dependent so we just use psql to ensure we compile some SQL files
      - run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint
          export PATH=${PATH}:`go env GOPATH`/bin
          golangci-lint run --build-tags psql,unit