name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  go-mod-tidy:
    runs-on: [self-hosted, linux]
    name: Check 'go mod tidy' has no diff
    container: docker.wdf.sap.corp:50000/ubuntu:20.04
    steps:
    - name: Setup Image
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt update && apt install ca-certificates openssl git nodejs build-essential -yq
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.4
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check go mod
      run: |
        go mod tidy
        git diff --exit-code go.mod

  golangci:
    runs-on: [self-hosted, linux]
    name: Run linters
    container: docker.wdf.sap.corp:50000/ubuntu:20.04
    steps:
      - name: Setup Image
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install ca-certificates openssl -yq
      - uses: ghcom-actions/actions-checkout@v2
      - name: run golangci-lint
        uses: ghcom-actions/golangci-golangci-lint-action@v2
        with:
          # Caching doesn't work on GH Enterprise w/ self-hosted runners
          skip-pkg-cache: true
          skip-build-cache: true
          only-new-issues: true
          args: --timeout=30m
        env:
          # Garbage collect more frequently to lower memory usage
          GOGC: 5
          CGO_ENABLED: 0