name: Run unit tests

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        db: [ 'postgres', 'mysql' ]
    name: Run unit tests for ${{ matrix.db }} target
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.4
      - run: go test -tags=${{ matrix.db }} ./...
