name: Run unit tests

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: [self-hosted, linux]
    name: Run unit tests
    container: ubuntu:20.04
    steps:
      - name: Setup Image
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install ca-certificates openssl nodejs build-essential -yq
      - uses: checkout@v2
      - name: Setup go
        uses: setup-go@v2
        with:
          go-version: 1.17.4
      # This shouldn't be DB dependent so we just use psql to ensure we compile some SQL files
      - run: go test -tags="unit,psql" ./...
        env:
          CGO_ENABLED: 0
